# Generated by Django 4.0 on 2021-12-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountes',
            fields=[
                ('AccounteId', models.AutoField(primary_key=True, serialize=False)),
                ('BankName', models.CharField(max_length=100)),
                ('AccounteBalance', models.IntegerField()),
                ('Wording', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('BankId', models.AutoField(primary_key=True, serialize=False)),
                ('BankName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('TransacDate', models.DateField()),
                ('Descriptive', models.CharField(max_length=200)),
                ('TransactionAmount', models.IntegerField()),
                ('TransactionType', models.CharField(choices=[('D', 'débité'), ('C', 'crédité')], max_length=1)),
                ('Accounte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankApp.accountes')),
            ],
        ),
    ]
